# (C) Copyright IBM Deutschland GmbH 2021
# (C) Copyright IBM Corp. 2021
# SPDX-License-Identifier: CC BY-NC-ND 3.0 DE
# - Simina Stefan <simina.stefan@ibm.com>

########################################################################################################################

apiVersion: v1
kind: Service
metadata:
  labels:
    app: tpm-simulator-1
  name: tpm-simulator-1
  namespace: %NAMESPACE%
spec:
  ports:
    - port: 2321
      protocol: TCP
      targetPort: 2321
      name: tpm-port
    - port: 2322
      protocol: TCP
      targetPort: 2322
      name: platform-port
  selector:
    app: tpm-simulator-1
  type: ClusterIP

########################################################################################################################
