# (C) Copyright IBM Deutschland GmbH 2021
# (C) Copyright IBM Corp. 2021
# SPDX-License-Identifier: CC BY-NC-ND 3.0 DE
# - Simina Stefan <simina.stefan@ibm.com>

########################################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpm-simulator-2
  namespace: %NAMESPACE%
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpm-simulator-2
      serverpod: tpm-simulator-2
  template:
    metadata:
      labels:
        app: tpm-simulator-2
        serverpod: tpm-simulator-2
    spec:
      imagePullSecrets:
        - name: %IMAGE_PULL_SECRET%
      containers:
        - name: tpm-simulator-2
          image: %ICR_INSTANCE%/%ICR_NAMESPACE%/tpm-client:%VERSION%
          imagePullPolicy: Always
          ports:
            - containerPort: 2321
              name: tpm-port
            - containerPort: 2322
              name: platform-port

########################################################################################################################
